baseURL = 'https://kristynad.github.io/263952_ZPC_25/'
languageCode = 'en-us'
title = 'Jak vytvořit (téměř) cokoliv'
theme = "ananke"

[ananke]
show_recent_posts = false

[markup.goldmark.renderer]
unsafe = false
