baseURL = 'https://kristynad.github.io/263952_ZPC_25/'
languageCode = 'cz-cs'
title = 'Jak vytvořit (téměř) cokoliv'
theme = "ananke"

[params.ananke]
show_recent_posts = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
